# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-04-19 12:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_category', models.CharField(default='\u7efc\u5408', max_length=50, verbose_name='\u6587\u7ae0\u7c7b\u522b')),
                ('article_create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u53d1\u8868\u65f6\u95f4')),
                ('article_title', models.CharField(max_length=50, verbose_name='\u6587\u7ae0\u6807\u9898')),
                ('article_content', models.TextField(default='', verbose_name='\u6587\u7ae0\u5185\u5bb9')),
                ('article_image', models.ImageField(upload_to='image/%Y/%m', verbose_name='\u6587\u7ae0\u914d\u56fe')),
                ('article_tag', models.CharField(max_length=20, verbose_name='\u6587\u7ae0\u6807\u7b7e')),
            ],
            options={
                'verbose_name': '\u6587\u7ae0',
                'verbose_name_plural': '\u6587\u7ae0',
            },
        ),
    ]
