# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-05-07 17:49
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_article_article_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_content',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='\u6587\u7ae0\u5185\u5bb9'),
        ),
    ]
