# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-04-19 12:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banner/%Y/%m', verbose_name='\u8f6e\u64ad\u56fe')),
                ('title', models.CharField(max_length=50, verbose_name='\u8f6e\u64ad\u5185\u5bb9\u6807\u9898')),
                ('text', models.CharField(max_length=50, verbose_name='\u8f6e\u64ad\u5185\u5bb9')),
                ('time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u53d1\u8868\u65f6\u95f4')),
                ('order', models.IntegerField(default=100, verbose_name='\u8f6e\u64ad\u987a\u5e8f')),
            ],
            options={
                'verbose_name': '\u9996\u9875\u8f6e\u64ad',
                'verbose_name_plural': '\u9996\u9875\u8f6e\u64ad',
            },
        ),
        migrations.CreateModel(
            name='My_imgae',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='my_image', verbose_name='\u4e2a\u4eba\u5934\u50cf')),
            ],
        ),
    ]
